[metadata]
name = openvpn-metrics
version = attr: ovpn_metrics.__version__
description = Collect and query per-client OpenVPN traffic metrics by attaching to tcpdump
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
keywords = openvpn, metrics, tcpdump, monitoring
classifiers =
    Environment :: Console
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Topic :: System :: Networking :: Monitoring

[options]
packages = ovpn_metrics
python_requires = >=3.8

[options.entry_points]
console_scripts =
    openvpn-metrics = ovpn_metrics.cli:main
